global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    relabel_configs:
      - source_labels: []
        target_label: instance
        replacement: 'odin'
      - source_labels: [__address__]
        target_label: __address__
        replacement: 'host.docker.internal:9100'
