services:
  grafana:
    image: grafana/grafana:latest
    container_name: infra_grafana
    restart: unless-stopped
    networks:
      - core-net
    ports:
      - '33000:3000'
    volumes:
      - /mnt/data/projects/infra/volumes/grafana:/var/lib/grafana
