services:
  grafana:
    image: grafana/grafana:latest
    container_name: infra_grafana
    restart: unless-stopped
    networks:
      - core-net
    ports:
      - '33000:3000'
    volumes:
      - grafana:/var/lib/grafana
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  grafana:
